name: domain
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../shared

  dartz:
  # DI
  get_it:
  injectable:

  freezed_annotation:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner:
  freezed:
  json_serializable:
  injectable_generator:
